name: Cache Rust dependencies
description: Cache Rust dependencies to speed up builds
inputs:
  cache-name:
    description: The name of the cache to use
    required: true
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      name: Cache Cargo registry
      id: cache-cargo-registry
      with:
        key: cargo-registry-${{ inputs.cache-name }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Cargo.lock') }}-${{ github.ref_name }}
        restore-keys: |
          cargo-registry-${{ inputs.cache-name }}-${{ runner.os }}-${{ runner.arch }}-main
          cargo-registry-${{ inputs.cache-name }}-${{ runner.os }}-${{ runner.arch }}-
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
    - uses: actions/cache@v4
      name: Cache Cargo target
      id: cache-cargo-target
      with:
        key: cargo-target-${{ inputs.cache-name }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Cargo.lock') }}-${{ github.ref_name }}
        restore-keys: |
          cargo-target-${{ inputs.cache-name }}-${{ runner.os }}-${{ runner.arch }}-main
          cargo-target-${{ inputs.cache-name }}-${{ runner.os }}-${{ runner.arch }}-
        path: |
          target/**
    - name: Set cache hit output
      shell: bash
      run: |
        echo "target-cache-hit=${{ steps.cache-cargo-target.outputs.cache-hit }}" >> $GITHUB_OUTPUT
        echo "registry-cache-hit=${{ steps.cache-cargo-registry.outputs.cache-hit }}" >> $GITHUB_OUTPUT
